name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: name=iPhone 11
          
          - sdk: macosx
            destination: arch=x86_64

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.3.1.app

    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing test-without-building \
          -workspace "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          ENABLE_TESTABILITY=YES | xcpretty -c;
      env:
        PROJECT: Pixela.xcworkspace
        SCHEME: Pixela
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
